export enum UserTypeEnum {
  AFFILIATE = 'AFFILIATE',
  ADMIN = 'ADMIN',
}

export enum UserRoleEnum {
  PORTO_ANALYST = 'PORTO_ANALYST',
  PORTO_ADMIN = 'PORTO_ADMIN',
  MESA_ADMIN = 'MESA_ADMIN',
}

export enum AffiliateStatusEnum {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum PixKeyTypeEnum {
  EMAIL = 'EMAIL',
  PHONE = 'PHONE',
  CPF = 'CPF',
}

export enum TokenPurposeEnum {
  SET_PASSWORD = 'SET_PASSWORD',
  RESET_PASSWORD = 'RESET_PASSWORD',
}

export enum AuthAudienceEnum {
  AFFILIATE = 'affiliate',
  ADMIN = 'admin',
}

export enum AuthErrorCodeEnum {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  REGISTRATION_UNDER_REVIEW = 'REGISTRATION_UNDER_REVIEW',
  REGISTRATION_REJECTED = 'REGISTRATION_REJECTED',
  PASSWORD_NOT_SET = 'PASSWORD_NOT_SET',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
}

export enum MailTemplateEnum {
  REGISTRATION_RECEIVED = 'REGISTRATION_RECEIVED',
  REGISTRATION_APPROVED = 'REGISTRATION_APPROVED',
  REGISTRATION_REJECTED = 'REGISTRATION_REJECTED',
  PASSWORD_RECOVERY = 'PASSWORD_RECOVERY',
}

export enum RegistrationErrorCodeEnum {
  INVALID_CPF = 'INVALID_CPF',
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  CPF_ALREADY_REGISTERED = 'CPF_ALREADY_REGISTERED',
  PIX_KEY_MISMATCH = 'PIX_KEY_MISMATCH',
  PIX_KEY_INVALID = 'PIX_KEY_INVALID',
  TERMS_NOT_ACCEPTED = 'TERMS_NOT_ACCEPTED',
  OUTDATED_TERMS = 'OUTDATED_TERMS',
  TERMS_NOT_PUBLISHED = 'TERMS_NOT_PUBLISHED',
}

/** Todo `code` que o corpo de erro da API pode carregar. */
export type ApiErrorCode = AuthErrorCodeEnum | RegistrationErrorCodeEnum;
